name: tag
description: The Tag class and friends
version: 0.6.5

author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/tag

environment:
  sdk: '>=1.24.2 <2.1.0'

dependencies:
  core:
    path: C:/acr/odw/sdk/core
    version: ^0.6.5
  vr:
    path: C:/odw/sdk/vr
    version: ^0.6.5

dev_dependencies:
  test: ^0.12.0
  test_tools:
    path: C:/odw/sdk/test_tools
    version: ^0.6.5

