name: tag
description: The Tag class and friends
version: 0.6.5

author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/tag

environment:
  sdk: '>=1.24.2 <2.1.0'

dependencies:
  dataset:
    path: C:/odw/sdk/dataset
    version: ^0.6.5
  system:
    path: C:/odw/sdk/system
    version: ^0.6.5

dev_dependencies:
  test: ^0.12.0
  test_tools:
    path: C:/odw/sdk/test_tools
    version: ^0.6.5
  timer:
    path: C:/odw/sdk/timer
    version: ^0.6.5
