name: tag
description: The Tag class and friends
version: 0.6.3

author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/tag

environment:
  sdk: '>=1.24.2 <2.1.0'

dependencies:
  date_time:
    path: C:/odw/sdk/date_time
    version: ^0.6.5
  number:
    path: C:/odw/sdk/number
    version: ^0.6.5
  string:
    path: C:/odw/sdk/string
    version: ^0.6.5
  system:
    path: C:/odw/sdk/system
    version: ^0.6.5
  uid:
    path: C:/odw/sdk/uid
    version: ^0.6.3

dev_dependencies:
  test: ^0.12.0
  test_tools:
    path: C:/odw/sdk/test_tools
    version: ^0.6.1
