name: tag
description: The Tag class and friends
version: 0.6.1

author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/tag

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  base:
    path: C:/odw/sdk/base
    version: ^0.6.1
  date_time:
    path: C:/odw/sdk/date_time
    version: ^0.6.1
  number:
    path: C:/odw/sdk/number
    version: ^0.6.0
  string:
    path: C:/odw/sdk/string
    version: ^0.6.1
  system:
    path: C:/odw/sdk/system
    version: ^0.6.1
  uid:
    path: C:/odw/sdk/uid
    version: ^0.6.1

dev_dependencies:
  test: ^0.12.0
  test_tools:
    path: C:/odw/sdk/test_tools
    version: ^0.6.0
